CLASS zcl_lab_12_linux_ccf DEFINITION
  PUBLIC
  INHERITING FROM zcl_lab_11_system_ccf
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_12_linux_ccf IMPLEMENTATION.
ENDCLASS.
